SystemPreferences/README.md

Signed-off-by: Chengwei Yang <me@chengweiyang.cn>

Yosemite is the latest Mac OS X now

---

iTerm/zsh.md

if the terminal still in the default shell, change default shell to zsh manually

change default shell to zsh manually

---

iTerm/README.md

change the link for Source Code Pro.  adobe -> adobe-fonts

Update iTerm README.md

---

Node.js/README.md

Changed an explicit version to the stable alias.

Minor improvement in the node setup

---

Python/ipython.md

A very small and useless commit to fix an typo.

Fixed a typo in ipython.md

---

LaTeX/README.md

Includes information about BasicTex and MacTex. Also explains the difference between BasicTex and MacTex.

MacTex and BasicTex information included

---

SUMMARY.md
Xcode/README.md

Fix capitalization of Xcode

---

MySql/README.md
iTerm/README.md

fix #66, #74 and update MySQL start info

update MySQL start info and iTerm2 color scheme

---

Ruby/README.md

Add rbenv-gemset to Ruby setup

---

Vim/README.md

Hi There, 
I add a page to add configuration about vim.
Please, take a look.

add details about vim

---

Python/README.md

Closes https://github.com/sb2nov/mac-setup/issues/75
Adds documentation about pyenv to ```Python/README.md```
Lines 3-5, 20-73

Adds pyenv method to install python

---

SystemPreferences/README.md

Add commands for ~auto-switching~ auto-swoosh disabling. I've found this annoying.

Add instructions for disabling workspace auto-switching

---

iTerm/zsh.md

It still shows up as code formatting.

Remove unnecessary indent

---

SystemPreferences/README.md

Fix a minor spelling / spacing error on the System Preferences README doc

Fix spelling in system pref readme

---

Homebrew/Usage.md

Correcting the location to Homebrew git folder

---

Homebrew/Cask.md

```
$ brew cask search airmail
No Cask found for "airmail".
```

Remove non-existing brew cask package from list

---

iTerm/fzf.md
publish_gitbook.sh

Introduce [fzf](https://github.com/junegunn/fzf)
In case someone does not know what fuzzy search is:
while in sublime text hit `⌘+p` and start typing...

Introduce fzf (cli fuzzy search)

---

Apps/README.md

As noted https://github.com/sb2nov/mac-setup/issues/127

Add Skim PDF viewer

---

Apps/README.md

As mentioned in https://github.com/sb2nov/mac-setup/issues/134
also alpha sorted

Add Mou.app

---

Git/gitignore.md

As of #135.
I am not sure about the wording (I guess it will be never perfect) the core information about setting up global Git ignore is there.
@sb2nov Just thumbs up here and I will follow up with merge etc.

Update .gitignore information

---

Go/README.md

https://golang.org/doc/code.html#GOPATH

Change go-workspace to go, to be inline with canonical usage:

---

SUMMARY.md
iTerm/ack.md

As promised (#131). Feel free to make changes to it.

Create section about ack

---

SUMMARY.md
contributors.py

This is merely a suggestion. When I read the original something felt off, in my head this new sentence sounds more correct. 
But it's just a suggestion. What do you think @sb2nov?

Update phrasing of meaning in contributors section

---

MySQL/README.md

Add terminal snippet to install sequel-pro from command line via homewbrew

Update MySQL readme.md

---

Makefile
book.json
package.json

Please review each commit by itself, because each commit is self-contained (kinda). These are all just suggestions, let me know if you guys want to change anything.
Also, in one commit I accidentally reformatted the entire `package.json`. Sorry. If you want to I can revert it and fix it up but I'd rather not since it'll require some work.

Configuration changes

---

Cpp/README.md

Link to section regarding the Xcode tools

Update CPP readme

---

book.json

Add the Google Analytics plugin. Fixes #158

---

.travis.yml

Add Travis CI integration; Fixes #162

---

README.md

View the preview in rendered markdown to see the actual result.

Add Travis status badge to README

---

.github/CONTRIBUTING.md
Apps/README.md
Docker/README.md
Git/README.md
Java/README.md
Makefile
Python/README.md
Python/pip.md
README.md
Ruby/README.md
SystemPreferences/README.md
Vim/README.md
book.json
package.json

* Closes #169 and includes its Makefile improvement.
* Resolves #164.

Unify macOS term

---

Docker/README.md
Docker/TipsAndTricks.md
Docker/UsefulCommands.md
SUMMARY.md

Docker commands + tricks

---

Emacs/README.md

Fix typos and add link

---

iTerm/README.md

- add quote from official website as description
- fix installation link and put note about Homebrew below installation text
- update list to not use capitals, remove traling dots
- improve shortcuts subsection

Improve iterm2 section - wording & grammar & links

---

SystemPreferences/README.md

- Enable repeat keys on press and hold
- Set Finder to not show 'All My Files' on open (to save memory)

Add macOS tips

---

Rust/README.md
SUMMARY.md

Referencing #112.
Didn't know what else to write about than how to install.
**Also, I can't remember how I installed Rust so it would be great if someone could verify this.**
_(For anyone who has not tried Rust I highly suggest it. I've completed the official book and a few projects and I really enjoy it. I'm still a novice but it has lots of interesting concepts and it's so much fun to write)_

Add section for Rust

---

SystemPreferences/README.md

Added:
-  how to change the default screenshots save location
Thank you for the guide!

Add SystemPreferences > User Defaults > screenshots save location

---

Security/README.md

Add Stronghold to Security Section

---

README.md

Might be a bit more useful like this

Link to CI rather than image

---

iTerm/ack.md
iTerm/fzf.md
iTerm/tree.md

The file with the most changes is the fzf file. I removed some information I thought was not useful and added some examples that I think "sells" the tool better, to display why it's useful.

Clean up and refresh iTerm sub pages

---

iTerm/zsh.md

The page felt a bit outdated so I updated it to use the latest download
links and added more information to it. Since this is the most viewed
page (according to Google Analytics) it deserves some love.

Update zsh page

---

Emacs/README.md
Homebrew/Cask.md
Homebrew/README.md
Homebrew/Usage.md
Python/virtualenv.md
SystemPreferences/README.md
iTerm/zsh.md
yarn.lock

I looked at the top viewed pages on Google Analytics and cleaned up like top 7 or so. Some stuff were pretty outdated. I considered removing the NTFS stuff for macOS version 10.11 and 10.12 but maybe it's useful for some people still on those versions.

General Cleanup

---

iTerm/README.md

iTerm2 source-code-pro
`brew tap caskroom/fonts && brew cask install font-source-code-pro`
https://github.com/adobe-fonts/source-code-pro

Add brew install Source Code Pro

---

Homebrew/Cask.md

[Betterzipql was merged into the cask betterzip](https://github.com/sindresorhus/quick-look-plugins#Plugins). This PR fixes #227.

Fixed betterzipql -> betterzip migration

---

Git/gitignore.md

Tool: **Git**
Installation
Usage
Customization
More

add step that makes usage of global file ~/.gitignore complete

---

LaTeX/README.md

- updated MacTex and BasicTex sections
- added note about tlmgr
- added VS Code as editor with a link for extension
- added note about PDF readers

Improve LaTeX section

---

Go/README.md

- simplify (shorten) overall text
- simplify example source-code
- reword some sections and update links
- remove GOROOT information, since its not needed anymore (go 1.9+)

Improve / update Go

---

iTerm/README.md

updated iterm2 shortcut key wording to match UI

---

PostgreSQL/README.md
SUMMARY.md

Added a document on Postgres installation on macOS
- Added a readme file containing the guidelines to install PostgreSQL
- updated the summary page with a link to the PostgreSQL readme

Added a installation doc for PostgreSQL

---

VisualStudioCode/README.md

Added recommended extensions useful for most developers, including Linting and settings that enable auto-formatting on "Save"

Auto-formatter and useful extensions for VS Code

---

Apps/README.md

Spectable is not actively maintained anymore. Rectangle is recommended by Spectacle former users.
https://github.com/eczarny/spectacle#important-note

Replace Spectacle with Rectangle

---

Homebrew/README.md

update homebrew install command

---

Homebrew/Cask.md
Homebrew/README.md

- Fix #254 
- Update a cask and links

Homebrew cask

---

Homebrew/Cask.md

* colloquy is an IRC client: https://www.slant.co/topics/1320/~best-irc-clients-for-mac, https://www.reddit.com/r/irc/comments/30vblf/best_irc_client_for_mac_users/
* homepage: http://colloquy.info/downloads.html
* brew formula: http://colloquy.info/downloads.html

add colloquy to suggested apps list

---

Docker/README.md
Java/sdkman.md

Adding SDKMan to the repository
Relevant Issue:
https://github.com/sb2nov/mac-setup/issues/201#issue-318911082

Sdkman Installation

---

Apps/README.md
Docker/README.md
SUMMARY.md
SublimeText/Plugins.md

Updated the formatting, added a submenu for sdkman and fixed a couple of non existent links

Fixing the formatting and the failing links

---

README.md
iTerm/README.md
scripts/publish_gitbook.sh

After the master branch was deleted, update the code to point to `main` branch instead of `master` branch
closes https://github.com/sb2nov/mac-setup/issues/298

Update references of the default branch from master to main

---

Apps/README.md

Fix Kaleidoscope link

---

Cpp/README.md
MyySQL/README.md
book.json
iTerm/README.md
iTerm/fzf.md

@sb2nov Please could you also update the one at the top-right of https://github.com/sb2nov/mac-setup?

Use HTTPS for https://sourabhbajaj.com

---

Apps/Octave.md
Docker/README.md
Emacs/README.md
Homebrew/Cask.md
LaTeX/README.md
MyySQL/README.md
Vagrant/README.md
VisualStudioCode/README.md
iTerm/README.md

Fixes https://github.com/sb2nov/mac-setup/issues/319.

Replace 'brew cask install' with 'brew install --cask'

---

Contributors.md
iTerm/zsh.md

Zsh Plugin Installation Instruction

---

SystemPreferences/README.md

add Filevault, Require Password immediately and Firewall

Add Security & Privacy Settings

---

Ruby/README.md

As per: https://github.com/sb2nov/mac-setup/issues/348
Also bump example Ruby version

Building older Ruby versions on M1 fix

---

.github/workflows/links.yml

I've been working hard on a new version of urlsup and I'm very curious
to see how it performs on a repo of this size.

Use new version of urlsup
