sb2nov/mac-setup

- Homebrew/README.md
Change path loading order globally by modifying `/private/etc/paths`.
> Add an alternative way to change paths for after Homebrew installation

- Apps/Octave.md
- Vagrant/README.md
Not all users know that homebrew-cask is not the standard homebrew plugin. In order to prevent confusion reference to installation of homebrew-cask has been added to Vagrant and Octava pages.
> Adding reference to homebrew-cask before use

- iTerm/zsh.md
The zsh part says use `env.sh` in order not to pollute `.zshrc`, but it doesn't include `env.sh` file in `.zshrc`, and the file name is `env.sh` in the sample config not `Env.sh`. So I changed all `Env.sh` to `env.sh`
> iTerm zsh add env.sh to .zshrc

- Docker/README.md
$ bbrew cask install dockertoolbox changed to $ brew cask install dockertoolbox
> Update Docker readme

- Apps/README.md
After 12 years of producing great Mac apps, Taco Software is closed. I’d like to offer a special thanks to all of you who supported Taco Software over the years. For those of you who purchased Taco HTML Edit or Latexian, limited support is still available if you need help recovering your license.
> Remove Latexian - no longer available

- Homebrew/Cask.md
```onepassword``` does not exist on Homebrew Cack, there is ```1password```
> Update Cask.md : onepassword -> 1password

- README.md
Looks like the markdown engine used for gitbooks doesn't work with the way the links were before.
> fix links not working

- Node.js/README.md
- SublimeText/Preferences.md
In [`SublimeText/Preferences.md`](https://github.com/sb2nov/mac-setup/compare/master...snood1205:subl-fix) `.DS_Store` is listed twice. Also I added an explicit command to `source ~/.bashrc` in the `nvm` install.
> Fix: Removed .DS_STORE duplicate

- Python/ipython.md
There should be no prerequisites for iPython installation, according to the official site: http://ipython.readthedocs.io/en/stable/install/install.html#installation-using-pip
Especially, web server frameworks and template engines like tornado and jinjia2 should never be the dependency of iPython. I suspect this part is copied from somewhere else that is irrelevant.
> fix: no prerequisites for iPython installation

- Docker/README.md
Use 'docker-toolbox' to install using brew cask.
> Fix docker-toolbox cask

- Python/virtualenv.md
Seems like `--distribute` option in `virtualenv` is outdated:  
https://virtualenv.pypa.io/en/stable/changes/#id38  
https://virtualenv.pypa.io/en/stable/reference/#cmdoption--distribute
> Remove '--distribute' option from Python/virtualenv.md

- SublimeText/Packages.md
The original code on this page would return an error when executed. Each version changes the snippet, so going to the source is the only sure way for it to work correctly.
> Adding link to workable code

- Tree/README.md
Add own section on `tree` command. I was not sure if it deserves it's own section, but I could not find a more appropriate place to put it. Maybe in the future, a collection of these "smaller" commands could be put under a single section.
Referencing #116.
> Add section on tree command

- Makefile
- scripts/publish_gitbook.sh
I'd like to propose we use a Makefile, this makes it easy to configure commands which can be all run from the root folder. No need to remember where any script is located, just run `make deploy` from the root folder. We started using this in my team at work a while back and it made things a lot easier. As you can see it's minimal configuration and it's an old convention a lot of people use.
What do you guys think?
> Introduce Makefile with deploy target

- JetBrains IDEs/README.md
Please review the markdown by first pressing the "View" button to see the rendered markdown.
I hope this text doesn't scream "I LOVE JETBRAINS" too much 😋  Any feedback is appreciated.
Is _JetBrains IDEs_ a good menu item name? It was the best I could come up with.
> Add section on JetBrains IDEs

- Docker/README.md
Currently http://sourabhbajaj.com/mac-setup/Docker/ links to http://sourabhbajaj.com/mac-setup/Docker/httpsL/https:/docs.docker.com/docker-for-mac/httpsL/https:/docs.docker.com/docker-for-mac/install which is an invalid url obviously
> Fixed invalid link

- Java/README.md
Java 9 changes the parameter format for `java_home`.
> Add JAVA_HOME setup command for Java9

- Git/README.md
* How to add ssh-keys to ssh-agent
* Example ssh config record
* How to add ssh-key to keychain
> Explain how to add ssh keys to the ssh-agent.

- Java/README.md
It seems rest of the guide is quite pro Homebrew where available, so was a bit odd that Java went by Oracle's installer route.
Not sure if I'm missing something though?
> Installing Java using Homebrew

- README.md
The GitBook link was pointing to a domain which seemed to infinitely redirect. Fixed it to use gitbook.com instead.
> Change GitBook URL in README

- Apps/Octave.md
This is a faster and easier way of installing Octave on OSX, still using Homebrew.
> Update Octave.md to recommend using Octave.app instead

- .github/ISSUE_TEMPLATE.md
Bug reports are always great but even better would be to clear about the fact that this guide should be a collaborative thing. And seeing the increase of bug reports lately I think we should address this.
Let me know what you think, or if I should re-phrase something.
> Add intent to issue template

- iTerm/zsh.md
In the `env.sh` example, the alias is incorrectly set as `alias git='g'` while it should be the other way around, the correct version being `alias g='git'`.
> Fix incorrect alias

- Heroku/README.md
Looks like `$ brew install heroku-toolbelt` throws an error now. 
Heroku docs suggest `$ brew install heroku/brew/heroku`
Error: No available formula with the name "homebrew/core/heroku"
==> Searching for a previously deleted formula (in the last month)...
Warning: homebrew/core is shallow clone. To get complete history run:
git -C "$(brew --repo homebrew/core)" fetch --unshallow
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
> update install command for heroku

- MyySQL/README.md
I added the note right in the first mention of `brew install` so end-user does not have to *reinstall* the MySQL if he/she wants to use Sequel Pro.
https://github.com/sequelpro/sequelpro/issues/2699
> Add note about unsupported MySQL version by Sequel Pro

- Apps/Settings.md
- Contributors.md
- Makefile
- References/README.md
- scripts/contributors.py
This is just a suggestion for a trivial styling change. "GitHub" and "GitBook" style their names with internal capitals. This PR changes mentions of them in the book to match their preferred styling.
> Capitalize GitHub and GitBook per their brands' styling

- Homebrew/README.md
This PR revises the Homebrew installation instructions to update them for Mojave and newer versions of macOS, and do some other tweaks.
Changes:
* `/usr/local/bin` is on the `$PATH` by default now in newer versions of macOS. (It's in `/etc/paths`.) This PR edits the instructions to tell you to only do the path changes if you're on an older OS.
* `/etc` is the more typical path to use for fiddling with the `/etc` files, I think, not `/private/etc`. `/etc` is the same location that other Unixes use; I don't think there's any reason to expose users to the details of `/private`.
* `$PATH` is already exported; there's no need to add an `export` statement when you're changing its values
* Added the command-line technique for installing the Xcode CLT
* I changed the `zsh` instructions to say "in …
> Update Homebrew instructions for Mojave and some other tweaks

- Homebrew/Cask.md
`brew cask search <package>` --changed--> `brew search <package>`
https://docs.brew.sh/Manpage#search-texttext
> brew cask search is deprecated

- iTerm/ack.md
I got a 404 for the current link. The section may have been removed, so just linked to the repo.
> Fix URL for the_silver_searcher in iterm/ack/alts

- iTerm/README.md
The current instructions to install source-code-pro was throwing an error:
```Error: caskroom/fonts was moved. Tap homebrew/cask-fonts instead.```
This PR fixes that.
> Updates brew install command for source-code-pro

- iTerm/zsh.md
Oh My Zsh plugin `colored-man` was renamed `colored-man-pages` upstream: https://github.com/ohmyzsh/ohmyzsh/commit/bb509dda236f8ed04b90806bc66f4ad1a41f57bc#diff-e0daa4091e1fc25d3c2ff19ed4613612
As a result, if you copy & paste the plugin list supplied, you end up with an error saying `colored-man` is not found. This PR corrects that.
> Fix suggested Oh My Zsh plugins

- Java/README.md
The tap `caskroom/versions` is no longer supported and has changed to
[`homebrew/cask-versions`](https://github.com/Homebrew/homebrew-cask-versions). Furthermore, the [recommended way for
installing Java via brew is to use the AdoptOpenJDK distribution](https://github.com/Homebrew/homebrew-cask-versions/issues/7253).
Also update the Oracle links with newer ones, with specific callout to
the login requirement for older JDK versions.
> Update install instructions for Java

- Java/README.md
Changes all the Java installation instructions to <strike>just tell everyone to use OpenJDK</strike> reflect how JDKs work in 2019 and later.
And the installation process is simpler now!
> Update Java installation instructions for 2020

- Docker/README.md
- Emacs/README.md
updating the documentation for Docker and Emac-mac documents.
Relevant issues:
https://github.com/sb2nov/mac-setup/issues/232#issue-389195473 - Docker installation having issues in Mac through brew
and 
https://github.com/sb2nov/mac-setup/issues/249#issue-410111739 - homebrew linkapps deprecated
> Docker and emac-mac documentation update

- Git/README.md
The guide has steps for using SSH and yet a few lines above that, it mentions that it'll use HTTPS.
Isn't SSH the new recommended method anyways?
> Include HTTPS instructions for Git and refine SSH instructions

- package.json
- scripts/generate_contributors.js
- scripts/publish_gitbook.sh
- yarn.lock
The python script required a virtualenv to have all of its
dependencies, or have them installed globally on your machine. Since
we're already installing dependencies using npm/yarn I figured we can
just add one more dependency and not have to worry about Python.
I've tested the new script and it outputs the exact same content as the
python script.
Let me know what you think!
> Remove Python dependency for deploying

- .travis.yml
- README.md
Updating the health-check branch to point to the `main` branch instead of the `master` branch.
Reference issue:  https://github.com/sb2nov/mac-setup/issues/298
> update health-check branch to point to the `main` branch instead of ` master`

- Apps/README.md
The current link for CheatSheet seems to be incorrect. It is linking to [http://www.grandtotal.biz/cheatsheet/](http://www.grandtotal.biz/cheatsheet/), which seems to be a completely different application than what is referenced by the text. The correct link is [https://mediaatelier.com/CheatSheet/](https://mediaatelier.com/CheatSheet/)
> Fix CheatSheet link

- VisualStudioCode/README.md
Added Live Server and vscode-icons to Visual Studio Code's useful extensions subsection.
> Add Live Server and vscode-icons to VSCode

- SublimeText/Plugins.md
https://sourabhbajaj.com/mac-setup/SublimeText/Plugins.html
Found by the CI healthcheck:
* https://travis-ci.org/github/sb2nov/mac-setup/jobs/725098628#L615
This link to https://bitbucket.org/StephaneBunel/pythonpep8autoformat is broken:
> - [Python PEP8 Autoformat](https://bitbucket.org/StephaneBunel/pythonpep8autoformat): Python PEP8 auto-format is a plugin to interactively reformat Python source code according to PEP-8
It must have been a Mercurial repo, which Bitbucket have shut down.
* https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket
Shall we remove it or replace it? If replace, with what?
> Remove broken plugin link

- JetBrainsIDEs/README.md
Direct users to install the JetBrains Toolbox App: a handy utility for installing JetBrains IDEs. Specifically useful for managing side-by-side installations of different versions of the same tool (stable, RC, EAP, etc.)
> Added installation section for using the JetBrains Toolbox App

- Node.js/README.md
There is a homebrew [formula](https://formulae.brew.sh/formula/nvm) for nvm. It is not "officially" supported by nvm, but it's always in line with the stable version. 
It works well and I believe it's better to include it instead of just displaying a script for a specific (now outdated) version of nvm.
> Add homebrew option to nvm installation

- PostgreSQL/README.md
https://brew.sh/2020/12/01/homebrew-2.6.0/
> Today I’d like to announce Homebrew 2.6.0. [...] brew commands replacing all `brew cask` commands [...]
```
brew cask install psequel
Updating Homebrew...
...
> Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
```
```
brew --version
Homebrew 2.6.1
```
> Calling brew cask install is deprecated from 2.6.0 (Dec 1st 2020)

- .github/workflows/test.yml
- .travis.yml
- Makefile
- README.md
Travis CI are going to shut down travis-ci.org by the end of the year, all projects need to migrate over to travis-ci.com. They've been moving resources over, hence the slow builds on .org.
https://docs.travis-ci.com/user/migrate/open-source-repository-migration
However, on .com there's a new pricing model. You'll get a certain number of credits to begin with. When they run out, you can either pay to subscribe, or contact support to apply for their new open source plan.
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
However, there are huge delays in support replying, if ever, and when they do they say they're waiting for approval from management, or someone recently was told that things are on hold pending more info from management.
I ran out of credits so couldn't build …
> Replace Travis CI with GitHub Actions

- .github/workflows/links.yml
- README.md
I figured out how to use urlsup with a decent API so we can migrate away
from Travis CI and instead use Github actions.
After this PR is merged:
cc @sb2nov @hugovk [at]anyone else that has input
> Use Github action for link validator

- Apps/Settings.md
Since e62d3b1754baabc8927d920e971fe11f1b717b6a Total Finder is no longer suggested to be installed and it is also discontinued(no support for Apple Silicon and upcoming versions of MacOS). I don't think this should be recommended for newly installed Macs, even if Total Finder is a nice addition. 
Post about the future of Total Finder: https://blog.binaryage.com/totalfinder-totalspaces-future/
> Remove suggested Total Finder changes.

- Homebrew/Cask.md
- Node.js/README.md
- iTerm/zsh.md
Suggest replacing older plugins for macOS 10.15+ with [Syntax Highlight](https://github.com/sbarex/SourceCodeSyntaxHighlight): supports most programming languages by default, many additional features/customisation
> Replace deprecated quick look extensions & minor housekeeping for checks

- iTerm/zsh.md
**Oh My Zsh** gave me a warning that the plugin `osx` has been renamed to `macos`. Changing to reflect the rename.
> Change plugin from osx to macos

- Rust/README.md
Although the package name "rustup" still works, in homebrew the new name for the same package is "rustup-init". See more (https://formulae.brew.sh/formula/rustup-init#default)
> Refactor with correct homebrew package name
